platform :ios,'8.0'
pod "GCDWebServer/WebDAV", "~> 3.0"
pod "LUKeychainAccess", "~> 1.2.4"
pod "PEAR-HttpFetcher-iOS"
pod "PEAR-FileManager-iOS"
pod "PEAR-URLParser-iOS"
pod "PEAR-BlocksKit-iOS"
pod "PEAR-PropertyListManager-iOS"
pod "PEAR-UIColorExtention-iOS"
pod "PEAR-KeyboardNotification-iOS"
pod "PEAR-AutoLayout-iOS"
pod "PEAR-Indicator-iOS"
pod "PEAR-CoreDataManager-iOS"
pod "PEAR-DateUnixTime-iOS"
pod "PEAR-DataConvertor-iOS"
pod "PEAR-ImageSlideViewer-iOS"